'use strict';

// Build the offline documentation portal from docs/**/*.md.
//
// Usage:
//   node tools/build-docs.js
//   node tools/build-docs.js --check
//   node tools/build-docs.js --watch
//   node tools/build-docs.js --root <repository-root>

const crypto = require('node:crypto');
const fs = require('node:fs');
const path = require('node:path');
const MarkdownIt = require('./vendor/markdown-it.min.js');

const GENERATED_NOTICE =
  '<!-- GENERATED FILE: edit docs/**/*.md, then run node tools/build-docs.js. Do not edit this file directly. -->\n';
const TEMPLATE_PLACEHOLDER = '__DOCS_DATA__';
const WATCH_DEBOUNCE_MS = 200;

const GROUP_DEFINITIONS = Object.freeze([
  { id: 'execution', title: 'اجرا و معماری', order: 10 },
  { id: 'product', title: 'محصول و مسیر یادگیری', order: 20 },
  { id: 'ux', title: 'طراحی و تجربهٔ کاربر', order: 30 },
  { id: 'quality', title: 'ممیزی و کیفیت', order: 40 },
  { id: 'content', title: 'محتوا و داده', order: 50 },
  { id: 'research', title: 'پژوهش و روش آموزش', order: 60 },
  { id: 'other', title: 'سایر مستندات', order: 90 },
]);

const GROUP_BY_ID = new Map(GROUP_DEFINITIONS.map(group => [group.id, group]));

// These files describe the shipped single-file trainer or point-in-time audits.
// They remain useful migration evidence, but they are not the source of truth for
// the Laravel/Android rebuild. New documents are not assumed to be legacy.
const LEGACY_DOCUMENTS = new Set([
  'data-corruption-audit.md',
  'dict-sources.md',
  'english-spelling-audit.md',
  'feature-map.md',
  'grammar-audit.md',
  'industry-scan.md',
  'jobs-content-methodology.md',
  'learning-path.md',
  'methodology.md',
  'sla-verdict.md',
  'translation-examples-audit.md',
  'ux-collocations.md',
  'ux-contrast.md',
  'ux-discussion.md',
  'ux-games-drills.md',
  'ux-grammar.md',
  'ux-listening.md',
  'ux-sentence-building.md',
  'ux-structure-plan.md',
  'ux-word-course.md',
  'vocabulary-categories.md',
]);

function compareStrings(left, right) {
  if (left < right) return -1;
  if (left > right) return 1;
  return 0;
}

function normalizeNewlines(value) {
  return String(value).replace(/^\uFEFF/u, '').replace(/\r\n?/g, '\n');
}

function toPosixPath(value) {
  return String(value).split(path.sep).join('/');
}

function shortHash(value, length = 8) {
  return crypto.createHash('sha256').update(String(value), 'utf8').digest('hex').slice(0, length);
}

function semanticSlug(value) {
  return String(value)
    .normalize('NFKC')
    .toLowerCase()
    .replace(/\u064a/gu, '\u06cc')
    .replace(/\u0643/gu, '\u06a9')
    .replace(/\p{M}+/gu, '')
    .replace(/[^\p{L}\p{N}]+/gu, '-')
    .replace(/-{2,}/g, '-')
    .replace(/^-|-$/g, '');
}

function safeSlug(value, fallbackPrefix = 'section') {
  const semantic = semanticSlug(value);
  const ascii = semantic
    .replace(/[^a-z0-9-]+/g, '')
    .replace(/-{2,}/g, '-')
    .replace(/^-|-$/g, '')
    .slice(0, 72);

  return ascii || `${fallbackPrefix}-${shortHash(semantic || String(value))}`;
}

function documentId(relativePath) {
  const withoutExtension = relativePath.replace(/\.md$/iu, '');
  return `doc-${safeSlug(withoutExtension, 'document')}-${shortHash(relativePath)}`;
}

function parseArguments(arguments_) {
  const options = {
    root: path.resolve(__dirname, '..'),
    check: false,
    watch: false,
  };

  for (let index = 0; index < arguments_.length; index += 1) {
    const argument = arguments_[index];

    if (argument === '--check') {
      options.check = true;
    } else if (argument === '--watch') {
      options.watch = true;
    } else if (argument === '--root') {
      const value = arguments_[index + 1];
      if (!value || value.startsWith('--')) throw new Error('--root requires a repository path.');
      options.root = path.resolve(value);
      index += 1;
    } else if (argument === '--help' || argument === '-h') {
      options.help = true;
    } else {
      throw new Error(`Unknown argument: ${argument}`);
    }
  }

  if (options.check && options.watch) throw new Error('--check and --watch cannot be used together.');
  return options;
}

function usage() {
  return [
    'Usage: node tools/build-docs.js [--root <repository-root>] [--check | --watch]',
    '',
    '  --check  Verify that docs/index.html is current without writing it.',
    '  --watch  Build once, then rebuild after Markdown files change.',
  ].join('\n');
}

function discoverMarkdownFiles(docsDirectory) {
  if (!fs.existsSync(docsDirectory)) throw new Error(`Documentation directory not found: ${docsDirectory}`);
  if (!fs.statSync(docsDirectory).isDirectory()) {
    throw new Error(`Documentation path is not a directory: ${docsDirectory}`);
  }

  const files = [];

  function visit(directory) {
    const entries = fs
      .readdirSync(directory, { withFileTypes: true })
      .sort((left, right) => compareStrings(left.name.toLowerCase(), right.name.toLowerCase()) || compareStrings(left.name, right.name));

    for (const entry of entries) {
      const absolutePath = path.join(directory, entry.name);

      // Never traverse junctions or symbolic links outside the documentation tree.
      if (entry.isSymbolicLink()) continue;
      if (entry.isDirectory()) {
        visit(absolutePath);
      } else if (entry.isFile() && /\.md$/iu.test(entry.name)) {
        const relativePath = toPosixPath(path.relative(docsDirectory, absolutePath));
        if (relativePath === '..' || relativePath.startsWith('../')) {
          throw new Error(`Documentation path escaped docs/: ${absolutePath}`);
        }
        files.push({ absolutePath, relativePath });
      }
    }
  }

  visit(docsDirectory);
  files.sort((left, right) => compareStrings(left.relativePath, right.relativePath));
  return files;
}

function inlineText(children) {
  if (!Array.isArray(children)) return '';

  return children
    .map(token => {
      if (token.type === 'softbreak' || token.type === 'hardbreak') return ' ';
      if (token.type === 'image') return token.content || '';
      if (token.type === 'html_inline') return String(token.content || '').replace(/[<>]/g, ' ');
      if (typeof token.content === 'string') return token.content;
      if (Array.isArray(token.children)) return inlineText(token.children);
      return '';
    })
    .join('')
    .replace(/\s+/gu, ' ')
    .trim();
}

function tokenText(token) {
  if (Array.isArray(token.children)) return inlineText(token.children);
  return String(token.content || '').replace(/[<>]/g, ' ').replace(/\s+/gu, ' ').trim();
}

function plainTextFromTokens(tokens) {
  const parts = [];

  for (const token of tokens) {
    if (token.type === 'inline') {
      const text = tokenText(token);
      if (text) parts.push(text);
    } else if (token.type === 'fence' || token.type === 'code_block') {
      const text = String(token.content || '').replace(/[<>]/g, ' ').replace(/\s+/gu, ' ').trim();
      if (text) parts.push(text);
    } else if (token.type === 'html_block') {
      // Raw HTML is disabled for rendering. Keep useful words searchable without
      // preserving a tag-shaped string in the search corpus.
      const text = String(token.content || '')
        .replace(/<[^>]*>/gu, match => ` ${match.slice(1, -1)} `)
        .replace(/\s+/gu, ' ')
        .trim();
      if (text) parts.push(text);
    }
  }

  return parts.join(' ').replace(/[<>]/g, ' ').replace(/\s+/gu, ' ').trim();
}

function truncate(value, maximum) {
  const text = String(value || '').replace(/\s+/gu, ' ').trim();
  if (text.length <= maximum) return text;
  const slice = text.slice(0, maximum + 1);
  const breakAt = Math.max(slice.lastIndexOf(' '), slice.lastIndexOf('،'));
  return `${slice.slice(0, breakAt > maximum * 0.6 ? breakAt : maximum).trimEnd()}…`;
}

function countWords(value) {
  const matches = String(value).match(/[\p{L}\p{N}]+(?:['’_-][\p{L}\p{N}]+)*/gu);
  return matches ? matches.length : 0;
}

function inferLanguageAndDirection(title, source) {
  const firstStrong = String(title).match(/[\p{Script=Arabic}A-Za-z]/u);
  const direction = firstStrong && /\p{Script=Arabic}/u.test(firstStrong[0]) ? 'rtl' : 'ltr';
  const rtlCount = (String(source).match(/\p{Script=Arabic}/gu) || []).length;
  const latinCount = (String(source).match(/[A-Za-z]/g) || []).length;
  return { lang: rtlCount >= latinCount ? 'fa' : 'en', dir: direction };
}

function inferGroup(relativePath) {
  const normalized = relativePath.toLowerCase();
  const basename = path.posix.basename(normalized);
  const segments = normalized.split('/');

  if (
    basename === 'execution_plan.md' ||
    segments.some(segment => ['architecture', 'adr', 'api', 'sync'].includes(segment))
  ) {
    return 'execution';
  }
  if (basename.startsWith('ux-') || segments.includes('ux')) return 'ux';
  if (basename.includes('audit') || basename.includes('corruption') || segments.includes('audits')) {
    return 'quality';
  }
  if (['feature-map.md', 'learning-path.md'].includes(basename) || segments.includes('product')) {
    return 'product';
  }
  if (
    ['dict-sources.md', 'jobs-content-methodology.md', 'vocabulary-categories.md'].includes(basename) ||
    segments.some(segment => ['content', 'data'].includes(segment))
  ) {
    return 'content';
  }
  if (
    ['industry-scan.md', 'methodology.md', 'sla-verdict.md'].includes(basename) ||
    segments.some(segment => ['research', 'references'].includes(segment))
  ) {
    return 'research';
  }
  return 'other';
}

function lifecycleMetadata(relativePath) {
  const normalized = relativePath.toLowerCase();
  const basename = path.posix.basename(normalized);

  if (normalized === 'execution_plan.md') {
    return {
      lifecycle: 'canonical',
      lifecycleLabel: 'مرجع زنده و رسمی',
      notice: 'این سند مرجع رسمی و به‌روز بازطراحی Laravel/Android است.',
    };
  }

  if (LEGACY_DOCUMENTS.has(normalized)) {
    let notice =
      'این سند یک snapshot مرجع از نسخهٔ قدیمی است؛ برای وضعیت فعلی بازطراحی، سند اجرایی را مبنا قرار دهید.';

    if (basename === 'methodology.md' || basename === 'learning-path.md') {
      notice =
        'این سند مرجع نسخهٔ قدیمی و بخشی از آن superseded است؛ sla-verdict و سند اجرایی جدیدترند.';
    } else if (basename === 'sla-verdict.md') {
      notice =
        'این سند مرجع نسخهٔ قدیمی است و بخشی از تصمیم‌های methodology و learning-path را جایگزین می‌کند.';
    }

    return {
      lifecycle: 'legacy',
      lifecycleLabel: 'مرجع نسخهٔ قدیمی',
      notice,
    };
  }

  return {
    lifecycle: 'supporting',
    lifecycleLabel: 'سند پشتیبان',
    notice: '',
  };
}

function createMarkdownRenderer() {
  const markdown = new MarkdownIt({
    html: false,
    linkify: false,
    typographer: false,
    breaks: false,
  });

  // Images would make the supposedly single-file portal perform a runtime
  // request. Render them as explicit references instead; links remain usable.
  markdown.renderer.rules.image = (tokens, index, options, environment, renderer) => {
    const token = tokens[index];
    const source = token.attrGet('src') || '';
    const title = token.attrGet('title');
    const alt = renderer.renderInlineAsText(token.children || [], options, environment) || 'تصویر';
    const safeSource = markdown.utils.escapeHtml(source);
    const safeAlt = markdown.utils.escapeHtml(alt);
    const safeTitle = title ? ` — ${markdown.utils.escapeHtml(title)}` : '';
    return `<span class="doc-image-reference" dir="auto">🖼 ${safeAlt}${safeTitle} <code>${safeSource}</code></span>`;
  };

  return markdown;
}

function annotateDocument(markdown, file) {
  const source = normalizeNewlines(fs.readFileSync(file.absolutePath, 'utf8'));
  const id = documentId(file.relativePath);
  const environment = {};
  const tokens = markdown.parse(source, environment);
  const headings = [];
  const headingCounts = new Map();
  const headingByFragment = new Map();

  for (let index = 0; index < tokens.length; index += 1) {
    const token = tokens[index];
    if (token.type !== 'heading_open') continue;

    const inline = tokens[index + 1];
    const text = inline && inline.type === 'inline' ? tokenText(inline) : '';
    const base = safeSlug(text || 'section');
    const count = (headingCounts.get(base) || 0) + 1;
    headingCounts.set(base, count);
    const uniqueBase = count === 1 ? base : `${base}-${count}`;
    const headingId = `${id}--${uniqueBase}`;
    token.attrSet('id', headingId);

    const heading = {
      id: headingId,
      text: text || 'بدون عنوان',
      level: Number(token.tag.slice(1)) || 2,
    };
    headings.push(heading);

    const semantic = semanticSlug(text);
    for (const key of [base, semantic, text.normalize('NFKC').toLowerCase()]) {
      if (key && !headingByFragment.has(key)) headingByFragment.set(key, headingId);
    }
  }

  const firstHeading = headings.find(heading => heading.level === 1) || headings[0];
  const title = firstHeading ? firstHeading.text : path.posix.basename(file.relativePath, path.posix.extname(file.relativePath));
  const summaryToken = tokens.find((token, index) => {
    if (token.type !== 'inline' || tokens[index - 1]?.type !== 'paragraph_open') return false;
    const text = tokenText(token);
    return text && text !== title;
  });
  const searchText = plainTextFromTokens(tokens);
  const wordCount = countWords(searchText);
  const group = inferGroup(file.relativePath);
  const language = inferLanguageAndDirection(title, source);

  return {
    id,
    relativePath: file.relativePath,
    source,
    tokens,
    environment,
    headings,
    headingByFragment,
    title,
    summary: truncate((summaryToken ? tokenText(summaryToken) : searchText).replace(/[<>]/g, ' '), 220),
    group,
    lang: language.lang,
    dir: language.dir,
    wordCount,
    readingMinutes: Math.max(1, Math.ceil(wordCount / 200)),
    searchText,
  };
}

function splitHref(href) {
  const match = String(href).match(/^([^?#]*)(\?[^#]*)?(#.*)?$/u);
  return match
    ? { pathname: match[1], query: match[2] || '', fragment: match[3] ? match[3].slice(1) : '' }
    : { pathname: String(href), query: '', fragment: '' };
}

function decodeUriComponentSafely(value) {
  try {
    return decodeURIComponent(value);
  } catch {
    return value;
  }
}

function routeFor(document, headingId = '') {
  return headingId ? `#doc/${document.id}/${headingId}` : `#doc/${document.id}`;
}

function resolveHeading(document, fragment) {
  if (!fragment) return '';
  const decoded = decodeUriComponentSafely(fragment).normalize('NFKC');
  if (document.headings.some(heading => heading.id === decoded)) return decoded;

  const candidates = [
    semanticSlug(decoded),
    safeSlug(decoded),
    decoded.toLowerCase(),
  ];
  for (const candidate of candidates) {
    const headingId = document.headingByFragment.get(candidate);
    if (headingId) return headingId;
  }
  return '';
}

function rewriteLinks(markdown, document, documentByPath) {
  function rewriteToken(token) {
    if (token.type === 'link_open') {
      const href = token.attrGet('href');
      if (href) {
        const parts = splitHref(href);
        const isExternal = /^(?:[a-z][a-z0-9+.-]*:|\/\/)/iu.test(parts.pathname);

        if (isExternal) {
          if (/^https?:/iu.test(parts.pathname)) {
            token.attrSet('target', '_blank');
            token.attrSet('rel', 'noopener noreferrer');
          }
        } else if (!parts.pathname) {
          const headingId = resolveHeading(document, parts.fragment);
          token.attrSet('href', routeFor(document, headingId));
        } else if (!parts.pathname.startsWith('/')) {
          const decodedPath = decodeUriComponentSafely(parts.pathname).replace(/\\/g, '/');
          const resolvedPath = path.posix.normalize(path.posix.join(path.posix.dirname(document.relativePath), decodedPath));
          const target = documentByPath.get(resolvedPath);

          if (target && /\.md$/iu.test(resolvedPath)) {
            token.attrSet('href', routeFor(target, resolveHeading(target, parts.fragment)));
          } else {
            const fragment = parts.fragment ? `#${parts.fragment}` : '';
            token.attrSet('href', `${resolvedPath}${parts.query}${fragment}`);
          }
        }
      }
    }

    if (Array.isArray(token.children)) token.children.forEach(rewriteToken);
  }

  document.tokens.forEach(rewriteToken);
  return markdown.renderer.render(document.tokens, markdown.options, document.environment);
}

function executionMetadata(documents) {
  const execution = documents.find(document => document.relativePath.toLowerCase() === 'execution_plan.md');
  const source = execution ? execution.source : '';
  const taskStats = { done: 0, todo: 0, blocked: 0, inProgress: 0 };
  const statusPattern = /^\|\s*`[A-Z][A-Z0-9-]*`\s*\|\s*(DONE|TODO|BLOCKED|IN PROGRESS)\s*\|/gmu;
  let match;

  while ((match = statusPattern.exec(source)) !== null) {
    const key = {
      DONE: 'done',
      TODO: 'todo',
      BLOCKED: 'blocked',
      'IN PROGRESS': 'inProgress',
    }[match[1]];
    taskStats[key] += 1;
  }

  const currentPhase = source.match(/^\*\*Current phase:\*\*\s*(.+)$/mu)?.[1]?.trim() || '';
  const nextTask = source.match(/^\*\*Next executable task:\*\*\s*(.+)$/mu)?.[1]?.trim() || '';
  return { taskStats, currentPhase, nextTask };
}

function buildPortalData(rootDirectory) {
  const docsDirectory = path.join(rootDirectory, 'docs');
  const files = discoverMarkdownFiles(docsDirectory);
  if (!files.length) throw new Error(`No Markdown documents found under ${docsDirectory}`);

  const markdown = createMarkdownRenderer();
  const annotated = files.map(file => annotateDocument(markdown, file));
  const documentByPath = new Map(annotated.map(document => [document.relativePath, document]));
  const groupCounts = new Map();

  for (const document of annotated) {
    groupCounts.set(document.group, (groupCounts.get(document.group) || 0) + 1);
  }

  annotated.sort((left, right) => {
    const leftOrder = GROUP_BY_ID.get(left.group)?.order ?? 999;
    const rightOrder = GROUP_BY_ID.get(right.group)?.order ?? 999;
    return leftOrder - rightOrder || compareStrings(left.relativePath, right.relativePath);
  });

  const orderWithinGroup = new Map();
  const docs = annotated.map(document => {
    const groupDefinition = GROUP_BY_ID.get(document.group) || GROUP_BY_ID.get('other');
    const lifecycle = lifecycleMetadata(document.relativePath);
    const order = orderWithinGroup.get(document.group) || 0;
    orderWithinGroup.set(document.group, order + 1);

    return {
      id: document.id,
      path: `docs/${document.relativePath}`,
      sourceHref: document.relativePath,
      title: document.title,
      summary: document.summary,
      group: document.group,
      groupTitle: groupDefinition.title,
      ...lifecycle,
      order,
      lang: document.lang,
      dir: document.dir,
      wordCount: document.wordCount,
      readingMinutes: document.readingMinutes,
      searchText: document.searchText,
      headings: document.headings,
      html: rewriteLinks(markdown, document, documentByPath),
    };
  });

  const canonicalHashInput = files
    .map(file => {
      const document = documentByPath.get(file.relativePath);
      return `${file.relativePath}\0${document.source}\0`;
    })
    .join('');
  const execution = executionMetadata(annotated);

  return {
    meta: {
      schemaVersion: 1,
      contentHash: crypto.createHash('sha256').update(canonicalHashInput, 'utf8').digest('hex'),
      totalDocs: docs.length,
      totalWords: docs.reduce((total, document) => total + document.wordCount, 0),
      totalHeadings: docs.reduce((total, document) => total + document.headings.length, 0),
      taskStats: execution.taskStats,
      currentPhase: execution.currentPhase,
      nextTask: execution.nextTask,
    },
    groups: GROUP_DEFINITIONS.filter(group => groupCounts.has(group.id)).map(group => ({
      ...group,
      count: groupCounts.get(group.id),
    })),
    docs,
  };
}

function serializeForHtml(value) {
  return JSON.stringify(value)
    .replace(/</g, '\\u003c')
    .replace(/>/g, '\\u003e')
    .replace(/&/g, '\\u0026')
    .replace(/\u2028/g, '\\u2028')
    .replace(/\u2029/g, '\\u2029');
}

function renderPortal(rootDirectory) {
  const templatePath = path.join(rootDirectory, 'tools', 'docs-template.html');
  if (!fs.existsSync(templatePath)) throw new Error(`Documentation template not found: ${templatePath}`);

  const template = normalizeNewlines(fs.readFileSync(templatePath, 'utf8'));
  const placeholderCount = template.split(TEMPLATE_PLACEHOLDER).length - 1;
  if (placeholderCount !== 1) {
    throw new Error(
      `Documentation template must contain ${TEMPLATE_PLACEHOLDER} exactly once; found ${placeholderCount}.`,
    );
  }

  const data = buildPortalData(rootDirectory);
  const rendered = template.replace(TEMPLATE_PLACEHOLDER, serializeForHtml(data));
  return {
    data,
    html: `${GENERATED_NOTICE}${rendered.replace(/^\uFEFF/u, '').replace(/\s*$/u, '')}\n`,
  };
}

function runBuild(rootDirectory, { check = false } = {}) {
  const outputPath = path.join(rootDirectory, 'docs', 'index.html');
  const mirrorPath = path.join(rootDirectory, 'technical-docs.html');
  const result = renderPortal(rootDirectory);
  const current = fs.existsSync(outputPath) ? fs.readFileSync(outputPath, 'utf8') : null;
  const currentMirror = fs.existsSync(mirrorPath) ? fs.readFileSync(mirrorPath, 'utf8') : null;
  const expected = result.html;
  const changed = current !== expected || currentMirror !== expected;

  if (check) {
    if (changed) {
      console.error('Documentation portal is stale. Run: node tools/build-docs.js');
      return { status: 1, changed: true, outputPath, mirrorPath, data: result.data };
    }
    console.log('Documentation portal is up to date.');
    return { status: 0, changed: false, outputPath, mirrorPath, data: result.data };
  }

  if (!changed) {
    console.log('Documentation portal already up to date.');
    return { status: 0, changed: false, outputPath, mirrorPath, data: result.data };
  }

  fs.writeFileSync(outputPath, expected, 'utf8');
  fs.writeFileSync(mirrorPath, expected, 'utf8');
  console.log(`Built docs/index.html and technical-docs.html from ${result.data.meta.totalDocs} Markdown documents.`);
  return { status: 0, changed: true, outputPath, mirrorPath, data: result.data };
}

function watchDocumentation(rootDirectory) {
  const docsDirectory = path.join(rootDirectory, 'docs');
  runBuild(rootDirectory);
  console.log('Watching docs/**/*.md for changes. Press Ctrl+C to stop.');

  let timer = null;
  const rebuild = () => {
    clearTimeout(timer);
    timer = setTimeout(() => {
      try {
        runBuild(rootDirectory);
      } catch (error) {
        console.error(`Documentation rebuild failed: ${error.message}`);
      }
    }, WATCH_DEBOUNCE_MS);
  };

  const watcher = fs.watch(docsDirectory, { recursive: true }, (eventType, filename) => {
    if (filename && !/\.md$/iu.test(toPosixPath(filename))) return;
    rebuild();
  });

  const close = () => {
    clearTimeout(timer);
    watcher.close();
    console.log('Documentation watcher stopped.');
  };
  process.once('SIGINT', close);
  process.once('SIGTERM', close);
  return watcher;
}

function main(arguments_ = process.argv.slice(2)) {
  let options;
  try {
    options = parseArguments(arguments_);
    if (options.help) {
      console.log(usage());
      return 0;
    }

    if (options.watch) {
      watchDocumentation(options.root);
      return 0;
    }

    return runBuild(options.root, { check: options.check }).status;
  } catch (error) {
    console.error(`Documentation portal build failed: ${error.message}`);
    return 2;
  }
}

module.exports = {
  GROUP_DEFINITIONS,
  annotateDocument,
  buildPortalData,
  countWords,
  discoverMarkdownFiles,
  documentId,
  main,
  parseArguments,
  renderPortal,
  resolveHeading,
  runBuild,
  safeSlug,
  semanticSlug,
  serializeForHtml,
  watchDocumentation,
};

if (require.main === module) {
  process.exitCode = main();
}
